### ISSUE TITLE
[bug] change multus CNI plugin type

### ISSUE THREAD

**Issue by harsh-kotak** [tele0x/free5gc-openshift#1]
The network attachment definitions in the init playbooks are using Multus CNI plug-in type as bridge instead of macvlan. Bridge type only allows pods to communicate if they are on the same host and not across hosts. That is why we need to switch to macvlan type. Read about different types [here](https://docs.openshift.com/container-platform/4.8/networking/multiple_networks/understanding-multiple-networks.html).

**Comment by harsh-kotak** [comment]
I have the playbook changes tested and verified in my lab. Let me know if I can submit a PR.

**Comment by tele0x** [comment]
Originally I was using Free5GC UPF as CNV (running as VM on OCP) because the gtp5g kernel module was not available for kernel 4.18 in RHCOS, until I changed gtp5g to compile on older kernels so I was able to load it on RHCOS using a daemonset. See below diagram, you can see how the bridge was used. Basically a NodeNetworkConfigurationPolicy with NMState to configure the bridge on the cluster interface. If you have multiple interfaces available on the server macvlan is the way to go for physical separation of the traffic or using vlans. PR are welcome, please feel free to submit one and thank you for your contribution!

![upf_vm](https://user-images.githubusercontent.com/2356078/145404223-504135f0-33d5-4bd1-b11a-edcce315bc9c.png)

**Comment by harsh-kotak** [comment]
Hi @tele0x I have submitted a PR for this. Please review.

**Comment by tele0x** [comment]
PR accepted. thank you for your work.
